name: tour_guide_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0
  

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  

  http: 1.3.0
  table_calendar: ^3.2.0
  sqflite: ^2.4.2
  path: ^1.9.1
             
  permission_handler: ^10.0.0  
  provider: ^6.0.0
  supabase_flutter: ^0.2.10

 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/image3.jpg
    - assets/images/image4.jpg
    - assets/images/image5.jpg
    - assets/images/splashscreen1.jpg
    - assets/images/splashscreen3.jpg
    - assets/images/slashscreen2.jpg
    - assets/images/travel.jpg
    - assets/images/guide1.jpg
    - assets/images/Guide2.jpg    
    - assets/images/guide3.jpg
    - assets/images/guide4.jpg
    - assets/images/guide5.jpg
    - assets/images/guide6.jpg
    - assets/images/guide7.jpg
    - assets/images/guide8.jpg
    - assets/images/guide9.jpg
    - assets/images/guide10.jpg
    - assets/images/guide11.jpg
    - assets/images/guide12.jpg
    - assets/images/guide13.jpg
    - assets/images/guide14.jpg
    - assets/images/guide15.jpg
  