name: tour_guide_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  

  http: 1.3.0
  table_calendar: ^3.2.0
  sqflite: ^2.4.2
  path: ^1.9.1
             
  permission_handler: ^10.0.0  
  supabase_flutter: 2.8.4
  provider: ^6.0.0

 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/image3.jpg
    - assets/images/image4.jpg
    - assets/images/image5.jpg
    - assets/images/splashscreen1.jpg
    - assets/images/splashscreen3.jpg
    - assets/images/slashscreen2.jpg