name: tour_guide_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0
  
dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.7.0
  google_fonts: ^6.1.0
  provider: ^6.0.0
  flutter_rating_bar: ^4.0.0
  table_calendar: ^3.2.0
  sqflite: ^2.4.2
  path: ^1.9.1
  permission_handler: ^12.0.0+1  
  image_picker: ^1.0.4
  uuid: 4.5.1
  shimmer: ^3.0.0
  flutter_svg: ^2.1.0
  flutter_staggered_animations: ^1.1.1
  file_picker: ^10.1.6
  webview_flutter: ^4.2.2
  video_player: ^2.8.0
  google_maps_flutter: ^2.5.0
  google_places_flutter: ^2.1.0
  flutter_tts: ^4.2.2
  geolocator: ^14.0.0
  supabase_flutter: ^2.9.0
  http: 1.4.0
  flutter_google_places_sdk: ^0.4.2+1
  url_launcher: ^6.1.14
  mobile_scanner: ^3.2.0 # For QR code scanning
  qr_flutter: 4.1.0 
  shared_preferences: ^2.5.2
  


 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/cities.html
    - assets/images/logo.png
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/image3.jpg
    - assets/images/image4.jpg
    - assets/images/image5.jpg
    - assets/images/splashscreen1.jpg
    - assets/images/splashscreen3.jpg
    - assets/images/slashscreen2.jpg
    - assets/images/travel.jpg
    - assets/images/guide1.jpg
    - assets/images/guide2.jpg    
    - assets/images/guide3.jpg
    - assets/images/guide4.jpg
    - assets/images/guide5.jpg
    - assets/images/guide6.jpg
    - assets/images/guide7.jpg
    - assets/images/guide8.jpg
    - assets/images/guide9.jpg
    - assets/images/guide10.jpg
    - assets/images/guide11.jpg
    - assets/images/guide12.jpg
    - assets/images/guide13.jpg
    - assets/images/guide14.jpg
    - assets/images/guide15.jpg
    - assets/images/destination1.jpg
    - assets/images/destination2.jpg
    - assets/images/destination3.jpg
    - assets/images/destination4.jpg
    - assets/images/destination5.jpg
    - assets/images/destination6.jpg
    - assets/images/destination7.jpg  
    - assets/images/destination8.jpg
    - assets/images/destination9.jpg  
    - assets/images/destination10.jpg
    - assets/images/peshawar1.jpg
    - assets/images/hunza.jpg
    - assets/images/fairymeadows.jpg
    - assets/images/babusartop.jpg
    - assets/images/skardu.jpg
    - assets/images/lahore1.jpg
    - assets/images/kashmir.jpg
    